sonar.projectKey=corgicorner_bisibility-sdk-python
sonar.projectName=bisibility-sdk-python
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=coverage/**,htmlcov/**,build/**,dist/**,graphify-out/**
sonar.coverage.exclusions=**/__init__.py
sonar.cpd.exclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
